### ISSUE TITLE
Date Panel Width

### ISSUE THREAD

**Issue by AustinRobinson** [shahabyazdi/react-multi-date-picker#21]
When I have the date format to show the day of the week and date it takes multiple lines. How can I widen the date panel to prevent this?

**Comment by shahabyazdi** [comment]
In your style.css :

```css
.rmpd-panel {
  min-width: size px; // default 125px
}

@media (max-width: 400px), (max-height: 400px) {
  .rmpd-panel {
    min-width: size px //default 103px;
  }
}
```

Use `!important` if not work.

Keep in mind that these numbers were the maximum value I could give to keep the panel mobile-friendly.
