### ISSUE TITLE
Change style of calendar

### ISSUE THREAD

**Issue by kunnan97** [shahabyazdi/react-multi-date-picker#71]
Is there a way I can change the style(color, fontweight) of the weekdays, the header and the on hover style?
![Screenshot 2021-10-27 143220](https://user-images.githubusercontent.com/69633828/139012080-416df097-0e25-45c8-b7ff-e875d215d99a.png)

**Comment by mannoeu** [comment]
> Is there a way I can change the style(color, fontweight) of the weekdays, the header and the on hover style? ![Screenshot 2021-10-27 143220](https://user-images.githubusercontent.com/69633828/139012080-416df097-0e25-45c8-b7ff-e875d215d99a.png)

First you must instantiate a class for your DatePicker. And change styles, like my example:

```javascript
 <DatePicker
     ...
     className={`closeer ${locale}`} 
     ...
  />
```
```css
:root {
  --rmdp-primary-closeer: #000000;
  --rmdp-secondary-closeer: #00796b;
  --rmdp-shadow-closeer: #26a69a;

  --rmdp-today-closeer: #cafff6;
  --rmdp-selected-closeer: #02e2bd;
  --rmdp-hover-closeer: #02e2bd;

  --rmdp-deselect-closeer: #00695c;
}

.rmdp-shadow.closeer {
  box-shadow: none;
}
.closeer * {
  font-family: "Muli";
  transition: all 0.2s ease;
}
.rmdp-container {
  width: 100%;
}

.closeer .rmdp-toolbar {
  position: absolute;
  right: 0;
  top: 0;
  z-index: 299;
}
.closeer .rmdp-border-top {
  border: none;
}
.closeer .rmdp-toolbar > div {
  display: flex;
  color: rgba(0, 0, 0, 0.54);
  background: transparent;
  align-items: center;
  justify-content: center;
  margin: 5px;

  border-radius: 50%;
  padding: 0.25rem;
  width: 2.5rem;
  height: 2.5rem;
  transition: all 0.2s ease;
  flex: none;
}

.closeer .rmdp-toolbar > div > svg {
  font-size: 0.975rem;
}

.closeer .rmdp-toolbar > div:hover {
  background: rgba(0, 0, 0, 0.04);
  box-shadow: none;
}

.closeer.rmdp-wrapper {
  border: none;
  box-shadow: none;
  border-radius: 16px;
  box-shadow: 0px 2px 6px rgb(0 0 0 / 10%);
}

.closeer .rmdp-header-values span {
  font-family: "Muli Bold";
  font-size: 14px;
}

.closeer .rmdp-calendar {
  padding: 11px 16px 16px;
  border-radius: 16px;
}

.closeer .rmdp-border-bottom {
  border: none;
}

.closeer .rmdp-calendar .rmdp-header {
  position: relative;
  min-height: 38px;
  height: 100%;
}
.closeer .rmdp-header:after {
  content: "";
  display: block;
  width: 100%;
  height: 1px;
  background: #d6d6d6;
  margin: 5px auto 0;
}

.closeer.en-US .rmdp-header:before {
  content: "Select dates";
  display: block;
  max-width: 94%;
  color: var(--rmdp-primary-closeer);
  margin: 0 auto 5px;
  font-family: "Muli Bold";
  font-size: 16px;
}

.closeer.es-ES .rmdp-header:before {
  content: "Seleccionar fechas";
  display: block;
  max-width: 94%;
  color: var(--rmdp-primary-closeer);
  margin: 0 auto 5px;
  font-family: "Muli Bold";
  font-size: 16px;
}

.closeer.pt-BR .rmdp-header:before {
  content: "Selecione as datas";
  display: block;
  max-width: 94%;
  color: var(--rmdp-primary-closeer);
  margin: 0 auto 5px;
  font-family: "Muli Bold";
  font-size: 16px;
}

.closeer .rmdp-panel-body li {
  background-color: var(--rmdp-primary-closeer);
  box-shadow: 0 0 2px var(--rmdp-secondary-closeer);
}

.closeer .rmdp-week-day {
  color: var(--rmdp-primary-closeer);
}

.closeer .rmdp-day.rmdp-deactive {
  color: var(--rmdp-secondary-closeer);
}

.closeer .rmdp-range {
  background-color: var(--rmdp-primary-closeer);
  box-shadow: 0 0 3px var(--rmdp-shadow-closeer);
}

.closeer .rmdp-arrow-container {
  align-items: center;
}

.closeer .rmdp-arrow {
  margin: 0;
  border: solid var(--rmdp-primary-closeer);
  border-width: 0 2px 2px 0;
  width: 6px;
  height: 6px;
  border-width: 0 1px 1px 0;
}

.closeer .rmdp-arrow-container.disabled .rmdp-arrow,
.closeer .rmdp-arrow-container.disabled:hover .rmdp-arrow {
  border-width: 0 1px 1px 0;
}

.closeer .rmdp-arrow-container {
  width: 28px;
  height: 28px;
}
.closeer .rmdp-arrow-container:hover:not(.disabled) {
  background-color: var(--rmdp-selected-closeer);
  box-shadow: none;
}

.closeer .rmdp-panel-body::-webkit-scrollbar-thumb {
  background: var(--rmdp-primary-closeer);
}

.closeer .rmdp-day.rmdp-today span {
  background-color: var(--rmdp-today-closeer);
  color: var(--rmdp-primary-closeer);
}

.closeer .rmdp-rtl .rmdp-panel {
  border-left: unset;
  border-right: 1px solid var(--rmdp-secondary-closeer);
}

.closeer .rmdp-day.rmdp-selected span:not(.highlight) {
  background-color: var(--rmdp-selected-closeer);
  box-shadow: none;
  color: var(--rmdp-primary-closeer);
}

.closeer .rmdp-day:not(.rmdp-day-hidden, .rmdp-disabled) span:hover {
  background-color: var(--rmdp-hover-closeer) !important;
  color: var(--rmdp-primary-closeer) !important;
}

.closeer .b-deselect {
  color: var(--rmdp-deselect-closeer);
  background-color: white;
}

.closeer .rmdp-action-button {
  color: var(--rmdp-primary-closeer);
}

.closeer .rmdp-button:not(.rmdp-action-button) {
  background-color: var(--rmdp-primary-closeer);
}

.closeer .rmdp-button:not(.rmdp-action-button):hover {
  background-color: var(--rmdp-deselect-closeer);
}
```
